version: '3'
services:
  ghost:
    image: ghost:1-alpine
    ports:
      - 2368:2368
    restart: always
    depends_on:
      - db
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: mysecret
      database__connection__database: ghost
    networks:
      - my-network
  db:
    image: mysql:5.7.40
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
    volumes:
      - my-volume:/var/lib/mysql
    networks:
      - my-network
volumes:
  my-volume:
networks:
  my-network: